### ISSUE TITLE
Implementar Tarjeta de Debito y Credito (análisis requerimientos nuevos y dar respuesta del precio).

### ISSUE THREAD

**Issue by eduardoportillo** [AlejandroChileno/Tapeke#10]
![image](https://user-images.githubusercontent.com/52632798/169959393-0a4ec52e-964c-41ce-8afa-1bb448f5e0e7.png)

URL: http://localhost:3000/pedido/confirmar?cantidad=3&envio=1&key=e3a2c71d-072c-4209-b32e-38938b756972&precio=15

**Comment by rickypazd** [comment]
Ya se realizo la integración con qhuantuy.
