### ISSUE TITLE
Falta Implementar  Configuración en el menu lateral  (Corregir ortografía) [Falta]

### ISSUE THREAD

**Issue by eduardoportillo** [AlejandroChileno/Tapeke#24]
![image](https://user-images.githubusercontent.com/52632798/161627403-a9b02a66-6857-4363-87a1-1abcf0b00342.png)

**Comment by eduardoportillo** [comment]
Definir si en configuraciónes se quita o se remplaza con ver perfil en la parte superior del menu lateral:

![image](https://user-images.githubusercontent.com/52632798/161628051-97133a17-2053-42d7-bc5a-969e2cf0b30c.png)

**Comment by rickypazd** [comment]
Configuración no estará en la app mobile 
va a ser una web aparte por eso se va a quitar
