### ISSUE TITLE
no funciona el botón como llegar en el menu de información de restaurantes [BUG]

### ISSUE THREAD

**Issue by eduardoportillo** [AlejandroChileno/Tapeke#29]
![image](https://user-images.githubusercontent.com/52632798/161629809-0afdac44-affd-4dbc-9a9f-f7e1b2f9dbe6.png)

Link: http://localhost:3000/restaurante/perfil?key=9e1a7498-1f5f-4df0-b97e-82b0cf3edbce

**Comment by alvarosiles11** [comment]
Close Issues

**Comment by eduardoportillo** [comment]
Se Cierra y se vuelve issus #38 [FALTA] implementar el botón como llegar en el menu de información de restaurantes y de la sección de comprar tapeke
