### ISSUE TITLE
[Falta] Restringir a cierta cantidad de caracteres la descripción de los restaurantes

### ISSUE THREAD

**Issue by eduardoportillo** [AlejandroChileno/Tapeke#4]

**Comment by Licethd** [comment]
Se está colocando como límite de 350 caracteres.

**Comment by eduardoportillo** [comment]
![image](https://user-images.githubusercontent.com/52632798/161634171-c41a7442-91af-4afa-b48c-f714e04f42fd.png)
![image](https://user-images.githubusercontent.com/52632798/161634209-f7b55eb6-ab7f-4082-b70a-dd85b1853024.png)
![image](https://user-images.githubusercontent.com/52632798/161634222-c86c0d58-4f93-4b34-8788-07c19f6f0bf2.png)


Sigue siendo muy grande la descripción
¿este restaurante cumple con los 350 chars o no?
Nota: el restanrante es Mirazur
