### ISSUE TITLE
[Falta] implementar boton de Detalles en el frame de reservar

### ISSUE THREAD

**Issue by eduardoportillo** [AlejandroChileno/Tapeke#5]
![image](https://user-images.githubusercontent.com/52632798/162850154-7ffe4abb-9c49-47ed-a57b-2dbb85ae2a13.png)

Link: http://127.0.0.1:3000/restaurante/perfil?key=96b7489a-019f-4a1c-a9e6-db157044945b

**Comment by alvarosiles11** [comment]
ya esta
