### ISSUE TITLE
[Falta] implementar la seccion que piensan otros usuarios en el frame de restaurantes

### ISSUE THREAD

**Issue by eduardoportillo** [AlejandroChileno/Tapeke#6]
![image](https://user-images.githubusercontent.com/52632798/162850230-76272e38-4b97-485d-8b52-7db9678c72fd.png)
Falta Implementar estadisticas segun las votaciones de los usuarios.

Link: http://127.0.0.1:3000/restaurante/perfil?key=96b7489a-019f-4a1c-a9e6-db157044945b

**Comment by alvarosiles11** [comment]
ya esta
